name: IngressFSTelegramBot
description: A sample command-line application.
# version: 1.0.0
# homepage: https://martinvylet.cz  
# author: Martin Výlet <vykend@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  teledart: ^0.0.32
  gsheets: ^0.1.1+1
  logging: ^0.11.3+2
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.7.0
 # test: ^1.5.0
